### PR TITLE
Add style formatting

### PR DESCRIPTION
**Pull request by toninorair**
Style formatting was provided:
some formatting messages were ignored:
1) Use nested module/class definitions instead of compact style
2) Missing top-level class documentation comment
3) Line is too long (in most cases provided for comments)
4) MethodLength should be no more than 10 symbols (ignore, max length - 19)
5) ModuleLength
6) Some spacing issues were ignored because some extra spaces were added on purpose to pretify the code
7)!!!!! ATTENTION STRANGE CASE (replacing '=' with '==' breakes functionality)
app/controllers/user_sessions_controller.rb:8:14: W: Lint/AssignmentInCondition: Assignment in condition - you probably meant to use ==.
    if @user = login(params[:email], params[:password], params[:remember])

Remaining issues are also explicable and can be left in the code:
Offenses:

app/controllers/password_resets_controller.rb:22:5: C: Style/GuardClause: Use a guard clause instead of wrapping the code inside a conditional expression.
    if @user.blank?
    ^^
app/controllers/password_resets_controller.rb:29:3: C: Metrics/AbcSize: Assignment Branch Condition size for update is too high. [19.21/15]
  def update
db/schema.rb:14:38: C: Style/NumericLiterals: Separate every 3 digits in the integer portion of a number with underscores(_).
ActiveRecord::Schema.define(version: 20150814161443) do
                                     ^^^^^^^^^^^^^^
lib/service/slack.rb:23:5: C: Metrics/AbcSize: Assignment Branch Condition size for users is too high. [31.26/15]
    def self.users
    ^^^
lib/service/trello.rb:52:5: C: Metrics/AbcSize: Assignment Branch Condition size for setup_users is too high. [15.56/15]
    def self.setup_users
    ^^^
lib/service/trello.rb:56:19: C: Style/Next: Use next to skip iteration.
      User.active.each do |db_user|
                  ^^^^
lib/service/trello.rb:65:5: C: Metrics/AbcSize: Assignment Branch Condition size for setup_academy_tasks is too high. [16.31/15]
    def self.setup_academy_tasks
    ^^^

82 files inspected, 8 offenses detected

### CODE REVIEW

**Comment by beornborn** [comment]
сделай rebase, видишь же что нельзя смержить

**Comment by beornborn** [comment]
лейблы ставь

**Comment by toninorair** [comment]
fix for merging

**Comment by toninorair** [comment]
fixes for merge

**Pull request closed without merging**
